/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aahowifi;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame; 
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
/**
 *
 * @author samsung
 */
public class aahoGUI extends javax.swing.JFrame {

    /**
     * Creates new form aahoGUI
     */
    public aahoGUI() {
        initComponents();
        init2();
    }

    private void init2(){
        prolay.setVisible(false);
        probtn.setToolTipText("Click to Create a new Hotspot Profile.");
        hotspot.setToolTipText("Click to Start the Hotspot.");
        Instructbtn.setToolTipText("How to configure Hotspot.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hotspot = new javax.swing.JToggleButton();
        prolay = new javax.swing.JLayeredPane();
        ssid = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        probtn = new javax.swing.JToggleButton();
        Instructbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("AAHO WIFI");

        hotspot.setText("Start Hotspot");
        hotspot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotspotActionPerformed(evt);
            }
        });

        jLabel2.setText("SSID( Hotspot Name)");

        jLabel3.setText("Password");

        javax.swing.GroupLayout prolayLayout = new javax.swing.GroupLayout(prolay);
        prolay.setLayout(prolayLayout);
        prolayLayout.setHorizontalGroup(
            prolayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prolayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ssid, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        prolayLayout.setVerticalGroup(
            prolayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prolayLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(prolayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        prolay.setLayer(ssid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        prolay.setLayer(pass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        prolay.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        prolay.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        probtn.setText("New Profile");
        probtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probtnActionPerformed(evt);
            }
        });

        Instructbtn.setText("Instructions");
        Instructbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(probtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(hotspot, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Instructbtn)
                        .addGap(280, 280, 280))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prolay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotspot)
                    .addComponent(probtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(prolay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Instructbtn)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotspotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotspotActionPerformed
   if(hotspot.isSelected()){
       hotspot.setToolTipText("Click to Stop the Hotspot.");
        hotspot.setText("Stop Hotspot");
        String command = "netsh wlan start hostednetwork";
        try 
{ 
Process p=Runtime.getRuntime().exec(command); 
p.waitFor(); 
BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
String line=reader.readLine(); 
String para = new String();
while(line!=null) 
{ 
    para = para+line;
line=reader.readLine(); 
}
JOptionPane.showMessageDialog(rootPane, para);
}
catch(IOException e1) {} 
catch(InterruptedException e2) {} 
}
else
{
          hotspot.setText("Start Hotspot");
          hotspot.setToolTipText("Click to Start the Hotspot.");
        String command = "netsh wlan stop hostednetwork";
        try 
{ 
Process p=Runtime.getRuntime().exec(command); 
p.waitFor(); 
BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
String line=reader.readLine(); 
String para = new String();
while(line!=null) 
{ 
    para = para+line;
line=reader.readLine(); 
}
JOptionPane.showMessageDialog(rootPane, para);
}
catch(IOException e1) {} 
catch(InterruptedException e2) {}       
}// TODO add your handling code here:     // TODO add your handling code here:
    }//GEN-LAST:event_hotspotActionPerformed

    private void probtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probtnActionPerformed
if(probtn.isSelected()==false)
{
    probtn.setText("New Profile");
    probtn.setToolTipText("Click to Create a new Hotspot Profile.");
        String command ;
command  = "netsh wlan set hostednetwork mode=allow ssid= ";
String user = ssid.getText();
String password = new String(pass.getPassword());
command = command+user;
command = command+" key= ";
command = command+password;
try 
{ 
Process p=Runtime.getRuntime().exec(command); 
p.waitFor(); 
BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
String line=reader.readLine(); 
JTextArea para = new JTextArea(10,45);
JScrollPane sp = new JScrollPane(para);
para.setEditable(false);
while(line!=null) 
{ 
    para.append(line);
    para.append("\n");
line=reader.readLine(); 
}
JOptionPane.showMessageDialog(null, sp);
}
catch(IOException e1) {} 
catch(InterruptedException e2) {} 
prolay.setVisible(false);
}
else{
    probtn.setToolTipText("Click to Create Hotspot Profile with SSID and Password entered below.");
    probtn.setText("Create Profile");
    prolay.setVisible(true);
}

// TODO add your handling code here:
    }//GEN-LAST:event_probtnActionPerformed

    private void InstructbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructbtnActionPerformed
     new Instructions().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_InstructbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aahoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aahoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aahoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aahoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aahoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Instructbtn;
    private javax.swing.JToggleButton hotspot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pass;
    private javax.swing.JToggleButton probtn;
    private javax.swing.JLayeredPane prolay;
    private javax.swing.JTextField ssid;
    // End of variables declaration//GEN-END:variables
}
